import Link from "next/link";
import Image from "next/image";
import type { Metadata } from "next";
import { BuyOnAmazon } from "@/components/BuyOnAmazon";
import { SamplePreview } from "@/components/SamplePreview";
import { SubscribeForm } from "@/components/SubscribeForm";
import { SiteFooter } from "@/components/SiteFooter";
import { BrandMark } from "@/components/BrandMark";
import { detectStoreCode } from "@/lib/detect-store";
import { storeUrl, AMAZON_LINK_REL } from "@/lib/amazon";
import { jsonLdScript } from "@/lib/jsonld";
import {
  BEST_RATING,
  getBookReviews,
  reviewSourceLabel,
  starString,
  formatReviewMonth,
} from "@/lib/reviews";

const ASIN = "B0GX33TZC3";
const SAMPLE_URL = "https://read.amazon.com/sample/B0GX33TZC3?clientId=share";
const BOOK_URL = "https://www.aftabarbiyani.com/books/the-probationers";

export const metadata: Metadata = {
  title: "The Probationers: A Psychological Mystery",
  description:
    "The Probationers by Aftab Arbiyani: six postulants, one snowbound abbey, a novice master dead beneath the bell tower. A locked-room mystery in Kindle & paperback.",
  alternates: {
    canonical: "/books/the-probationers",
  },
  openGraph: {
    siteName: "Aftab Arbiyani",
    locale: "en_US",
    title: "The Probationers: A Psychological Mystery Novel by Aftab Arbiyani",
    description:
      "Six postulants. One snowbound abbey. A novice master found dead beneath the bell tower. A locked-room mystery about faith, belonging, and secrecy.",
    url: "/books/the-probationers",
    type: "book",
    // og:image is generated by the opengraph-image.tsx card in this segment.
  },
  twitter: {
    card: "summary_large_image",
    title: "The Probationers: A Psychological Mystery Novel by Aftab Arbiyani",
    description:
      "Six postulants. One snowbound abbey. A novice master found dead beneath the bell tower. A locked-room mystery about faith, belonging, and secrecy.",
    // twitter:image is generated from the opengraph-image.tsx card too.
  },
};

// Two editions of one work. The buy links route through the reader's regional
// Amazon store (BuyOnAmazon); the structured data below lists both formats so
// search and AI engines know the book exists in ebook and print.
//
// Built as a function because the rating data is fetched per request (Amazon
// reviews merged with author-approved ARC reviews). The aggregateRating and
// review keys are omitted entirely when there are no reviews, rather than
// emitting a zero-count aggregate.
function buildBookJsonLd({
  aggregateRatingJsonLd,
  reviewsJsonLd,
}: {
  aggregateRatingJsonLd?: object;
  reviewsJsonLd?: object[];
}) {
  return {
  "@context": "https://schema.org",
  "@type": "Book",
  "@id": "https://www.aftabarbiyani.com/#book-the-probationers",
  name: "The Probationers",
  url: BOOK_URL,
  author: { "@id": "https://www.aftabarbiyani.com/#person" },
  inLanguage: "en",
  genre: "Psychological Mystery",
  datePublished: "2026-05-15",
  image: "https://www.aftabarbiyani.com/the-probationers-cover.jpeg",
  description:
    "Six postulants. One snowbound Benedictine abbey in the Umbrian hills. A novice master found dead beneath the bell tower, and a truth hidden inside a lifetime of devotion. A locked-room mystery about faith, belonging, and the private bargains people make to remain inside the worlds they love.",
  ...(aggregateRatingJsonLd ? { aggregateRating: aggregateRatingJsonLd } : {}),
  ...(reviewsJsonLd?.length ? { review: reviewsJsonLd } : {}),
  workExample: [
    {
      "@type": "Book",
      "@id": "https://www.aftabarbiyani.com/#book-the-probationers-ebook",
      bookFormat: "https://schema.org/EBook",
      inLanguage: "en",
      author: { "@id": "https://www.aftabarbiyani.com/#person" },
      url: "https://www.amazon.com/dp/B0GX33TZC3",
      potentialAction: {
        "@type": "ReadAction",
        target: "https://www.amazon.com/dp/B0GX33TZC3",
      },
      offers: {
        "@type": "Offer",
        availability: "https://schema.org/InStock",
        url: "https://www.amazon.com/dp/B0GX33TZC3",
      },
    },
    {
      "@type": "Book",
      "@id": "https://www.aftabarbiyani.com/#book-the-probationers-paperback",
      bookFormat: "https://schema.org/Paperback",
      isbn: "9798197795472",
      numberOfPages: 361,
      inLanguage: "en",
      author: { "@id": "https://www.aftabarbiyani.com/#person" },
      url: "https://www.amazon.com/dp/B0GX33TZC3",
      offers: {
        "@type": "Offer",
        availability: "https://schema.org/InStock",
        url: "https://www.amazon.com/dp/B0GX33TZC3",
      },
    },
  ],
  };
}

const breadcrumbJsonLd = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    {
      "@type": "ListItem",
      position: 1,
      name: "Home",
      item: "https://www.aftabarbiyani.com",
    },
    {
      "@type": "ListItem",
      position: 2,
      name: "The Probationers",
      item: BOOK_URL,
    },
  ],
};

const questions = [
  {
    question: "Is The Probationers available in paperback and ebook?",
    answer:
      "Yes. The Probationers is available on Amazon as a Kindle ebook and as a 361-page paperback, and ships internationally.",
  },
  {
    question: "Is it a standalone novel or part of a series?",
    answer:
      "It is a standalone debut novel with a complete, self-contained mystery. A second mystery is already underway.",
  },
  {
    question: "What kind of mystery is it?",
    answer:
      "A closed-circle, locked-room whodunit with psychological depth, set inside a snowbound Benedictine monastery. It is written for readers of Agatha Christie and Tana French.",
  },
  {
    question: "Can I read a sample before buying?",
    answer:
      "Yes. You can read the opening pages of The Probationers for free through Amazon's Kindle sample.",
  },
  {
    question: "Can I buy it outside the United States?",
    answer:
      "Yes. The buy links on this page route to your regional Amazon store, and you can switch stores manually if you prefer a different marketplace.",
  },
];

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: questions.map((item) => ({
    "@type": "Question",
    name: item.question,
    acceptedAnswer: {
      "@type": "Answer",
      text: item.answer,
    },
  })),
};

const details = [
  "Murder Mystery",
  "Umbrian Monastery",
  "Kindle & Paperback",
  "361 pages",
];

export default async function TheProbationersPage() {
  const [storeCode, { reviews, averageRating, reviewCount, aggregateRatingJsonLd, reviewsJsonLd }] =
    await Promise.all([detectStoreCode(), getBookReviews("the-probationers")]);

  const bookJsonLd = buildBookJsonLd({ aggregateRatingJsonLd, reviewsJsonLd });

  return (
    <main>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: jsonLdScript(bookJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: jsonLdScript(breadcrumbJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: jsonLdScript(faqJsonLd) }}
      />

      <section className="simpleHero">
        <nav className="nav" aria-label="Primary">
          <Link className="brand" href="/">
            <BrandMark size={26} className="brandMark" />
            Aftab Arbiyani
          </Link>
          <div className="navLinks">
            <Link href="/about">About</Link>
            <Link href="/#books">Books</Link>
            <Link href="/blog">Blog</Link>
          </div>
        </nav>
        <div className="simpleHeroCopy">
          <p className="eyebrow">The book</p>
          <h1>The Probationers</h1>
          <p className="lede">
            Six postulants. One snowbound abbey. A novice master found dead
            beneath the bell tower, and a truth hidden inside a lifetime of
            devotion.
          </p>
          <div className="actions">
            <BuyOnAmazon
              asin={ASIN}
              initialCode={storeCode}
              variant="primary"
              showSwitcher={false}
              label="Get The Probationers"
            />
            <a className="button secondary" href="#synopsis">
              Read the synopsis
            </a>
          </div>
        </div>
      </section>

      <section className="booksSection">
        <div className="bookShelf">
          <article
            className="bookCard"
            aria-label="The Probationers, buy options"
          >
            <div className="bookCover">
              <Image
                className="bookCoverImg"
                src="/the-probationers-cover.jpeg"
                alt="Cover of The Probationers by Aftab Arbiyani"
                fill
                sizes="(max-width: 820px) 260px, 260px"
                quality={90}
                priority
              />
            </div>
            <div className="bookInfo">
              <span>Available now · Kindle &amp; paperback</span>
              <p className="bookGenre">Psychological Murder Mystery / Whodunit</p>
              <p>
                A locked-room mystery set inside a Benedictine monastery in the
                Umbrian hills, where six novices, one body, and sixty-four years
                of buried secrets converge. Available as a Kindle ebook and a
                361-page paperback.
              </p>
              {reviewCount > 0 && (
                <p
                  className="ratingSummary"
                  aria-label={`Rated ${averageRating} out of ${BEST_RATING} from ${reviewCount} reader reviews`}
                >
                  <span className="ratingStars" aria-hidden="true">
                    {starString(averageRating)}
                  </span>
                  {averageRating.toFixed(1)} · {reviewCount} reader{" "}
                  {reviewCount === 1 ? "review" : "reviews"}
                </p>
              )}
              <div className="bookMeta">
                <span>Paperback ISBN 9798197795472</span>
                <BuyOnAmazon
                  asin={ASIN}
                  initialCode={storeCode}
                  variant="bare"
                  showSwitcher
                  label="Buy on Amazon"
                />
              </div>
              <SamplePreview sampleUrl={SAMPLE_URL} title="The Probationers" />
              <a
                className="textLink"
                href={storeUrl(storeCode, ASIN)}
                target="_blank"
                rel={AMAZON_LINK_REL}
              >
                Read reader reviews on Amazon ↗
              </a>
            </div>
          </article>
        </div>
      </section>

      <section className="section split" id="synopsis">
        <div>
          <p className="eyebrow">Synopsis</p>
          <h2>Belonging can become a locked room.</h2>
        </div>
        <div className="prose">
          <p>
            At the Abbazia di San Gerolamo, a Benedictine monastery high in the
            Umbrian hills, six postulants are halfway through the year that will
            decide the rest of their lives. On the morning of the mid-winter
            feast, the novice master, Father Tomaso Ricci, is found at the foot
            of the bell tower. It looks like a fall. It isn&apos;t. And by
            nightfall the snow has closed every road off the mountain.
          </p>
          <p>
            Sister Aude Bellamy, a Dominican canon lawyer and former French
            magistrate, is sent to establish what happened before the civil
            authorities can reach the abbey. What she finds is a community bound
            by the Great Silence, where each postulant is guarding a secret they
            would do almost anything to keep, and where the line between
            confession and survival has quietly disappeared.
          </p>
          <p>
            The Probationers is a locked-room mystery about belonging and exile,
            about what a person will do to stay inside the world they have built
            for themselves. It is written for readers who believe a mystery
            should earn its ending.
          </p>
        </div>
      </section>

      <section className="detailBand">
        {details.map((item) => (
          <div className="detail" key={item}>
            {item}
          </div>
        ))}
      </section>

      <section className="section">
        <div>
          <p className="eyebrow">The puzzle</p>
          <h2>The body is on the wrong side of the tower.</h2>
        </div>
        <div className="prose">
          <p>
            The Great Silence should protect the life of the community. Instead,
            it hides a murder. A fall from the belfry window would have put the
            body in the inner court; instead it lies on the garden side of the
            tower, where no accident could have placed it. One door was locked
            from the inside. One key was in the dead man&apos;s own pocket.
          </p>
          <p>
            To find the truth, Sister Aude has to weigh vows against fear and
            obedience against motive, and confront her own instinct to trust the
            people an institution has taught everyone to trust. Every closed
            system has its own logic. This one has kept its secrets for
            sixty-four years.
          </p>
        </div>
      </section>

      <section className="section">
        <div>
          <p className="eyebrow">For readers of</p>
          <h2>Christie&apos;s puzzles, French&apos;s psychology.</h2>
        </div>
        <div className="prose">
          <p>
            If you love the closed-circle puzzles of Agatha Christie, the
            psychological weather of Tana French, or the cloistered dread of{" "}
            <em>The Name of the Rose</em>, The Probationers is written for you: a
            fair-play whodunit that treats its suspects as people rather than
            mechanisms, and an ending that means to be earned.
          </p>
          <p>
            <SamplePreview sampleUrl={SAMPLE_URL} title="The Probationers" />
          </p>
        </div>
      </section>

      <section className="section split" id="reviews">
        <div>
          <p className="eyebrow">Reader reviews</p>
          <h2>What readers say.</h2>
          {reviewCount > 0 && (
            <p
              className="ratingSummary"
              aria-label={`Rated ${averageRating} out of ${BEST_RATING} from ${reviewCount} reader reviews`}
            >
              <span className="ratingStars" aria-hidden="true">
                {starString(averageRating)}
              </span>
              {averageRating.toFixed(1)} · {reviewCount} reader{" "}
              {reviewCount === 1 ? "review" : "reviews"}
            </p>
          )}
        </div>
        <div className="prose">
          <div className="reviewList">
            {reviews.map((r) => (
              <figure className="reviewCard" key={`${r.source}-${r.name}-${r.date}`}>
                <div className="reviewStars" aria-hidden="true">
                  {starString(r.rating)}
                </div>
                <p className="reviewTitle">{r.title}</p>
                <blockquote className="reviewQuote">{r.body}</blockquote>
                <figcaption className="reviewMeta">
                  {r.name} · {reviewSourceLabel(r.source)} ·{" "}
                  {formatReviewMonth(r.date)}
                </figcaption>
              </figure>
            ))}
          </div>
          <a
            className="textLink"
            href={storeUrl(storeCode, ASIN)}
            target="_blank"
            rel={AMAZON_LINK_REL}
          >
            Read the reviews on Amazon ↗
          </a>
        </div>
      </section>

      <section className="section questions" id="questions">
        <div className="sectionHeader">
          <p className="eyebrow">Q&amp;A</p>
          <h2>Reader Questions</h2>
        </div>
        <div className="questionList">
          {questions.map((item) => (
            <details className="questionItem" key={item.question}>
              <summary>
                <span className="questionText">{item.question}</span>
                <span className="questionIcon" aria-hidden="true" />
              </summary>
              <p>{item.answer}</p>
            </details>
          ))}
        </div>
      </section>

      <section className="subscribeSection" id="subscribe">
        <div>
          <p className="eyebrow">Newsletter</p>
          <h2>Get early access to the next mystery.</h2>
          <p className="arcCrossLink">
            Want to read it before publication?{" "}
            <Link className="textLink" href="/arc">
              Apply to the ARC reader team →
            </Link>
          </p>
        </div>
        <SubscribeForm />
      </section>

      <SiteFooter />
    </main>
  );
}
